; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27025.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Administrator\AppData\Local\Temp\2\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
