############################################################################
#
#  Program:  OpenSees
#
#  Purpose:  A Top-level Makefile to create the libraries needed
#	     to use the OpenSees framework. Works on Linux version 6.1
#            and below.
#
#  Written: fmk 
#  Created: 10/99
#
#  Send bug reports, comments or suggestions to fmckenna@ce.berkeley.edu
#
############################################################################

# %---------------------------------%
# |  SECTION 1: PROGRAM             |
# %---------------------------------%
#
# Specify the location and name of the OpenSees interpreter program
# that will be created (if this all works!)

minjie = /home/mhscott/OpenSees
#minjie = ~/Dropbox/OpenSees
libpath = ~/lib
libpath = /home/mhscott/lib
paralleldir = $(minjie)/PARALLEL_NUMERICAL_LIBS
mpidir = $(paralleldir)/mpich-install
mumpsdir = $(paralleldir)/MUMPS_4.10.0
scalapackdir = $(paralleldir)/scalapack-2.0.2

OpenSees_PROGRAM = ~/bin/OpenSees
PROGRAMMING_MODE = SEQUENTIAL
# PROGRAMMING_MODE = PARALLEL_INTERPRETERS
# PROGRAMMING_MODE = PARALLEL

ifeq ($(PROGRAMMING_MODE), PARALLEL_INTERPRETERS)
    PROGRAMMING_FLAG = -D_PARALLEL_INTERPRETERS
endif

ifeq ($(PROGRAMMING_MODE), PARALLEL)
    PROGRAMMING_FLAG = -D_PARALLEL_PROCESSING
endif

OPERATING_SYSTEM = LINUX

GRAPHICS = UsingOpenGL
GRAPHIC_FLAG = -D_GLX
#GRAPHICS = NONE
#GRAPHIC_FLAG = -D_NOGRAPHICS


DEBUG_MODE = DEBUG
DEBUG_MODE = NO_DEBUG

#RELIABILITY = NO_RELIABILITY
RELIABILITY = YES_RELIABILITY
RELIABILITY_FLAG = -D_RELIABILITY

PFEM_FLAG = -D_PFEM -D_AMGCL
ITPACK_FLAG = -D_ITPACK

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    MUMPS_FLAG = 
    HAVEMUMPS = 
    MUMPS = 
else
    MUMPS_FLAG = -D_MUMPS
    HAVEMUMPS = YES
    MUMPS = YES
endif

# %---------------------------------%
# |  SECTION 2: PATHS               |
# %---------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries or if you have
# any of the libraries already leave the directory location blank AND
# remove the directory from DIRS.

FE		= $(minjie)/SRC

BLASdir      = $(minjie)/OTHER/BLAS
CBLASdir     = $(minjie)/OTHER/CBLAS
LAPACKdir    = $(minjie)/OTHER/LAPACK
SUPERLUdir   = $(minjie)/OTHER/SuperLU_5.1.1/SRC
ARPACKdir    = $(minjie)/OTHER/ARPACK
UMFPACKdir   = $(minjie)/OTHER/UMFPACK
ITPACKdir   = $(minjie)/OTHER/ITPACK
AMDdir       = $(minjie)/OTHER/AMD
CSPARSEdir   = $(minjie)/OTHER/CSPARSE
TRIANGLEdir   = $(minjie)/OTHER/Triangle
TETGENdir   = $(minjie)/OTHER/tetgen1.4.3
SRCdir       = $(minjie)/SRC

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    SUPERLU_DISTdir =
    SUPERLU_INCLUDES =
    METISdir       =
else
    SUPERLU_DISTdir = $(minjie)/OTHER/SuperLU_DIST_2.5/SRC
    SUPERLU_INCLUDES = -I$(SUPERLU_DISTdir)
    METISdir       = $(minjie)/OTHER/METIS
endif

DIRS    = $(BLASdir) $(CBLASdir) $(LAPACKdir) $(ITPACKdir) $(SUPERLUdir) $(ARPACKdir) $(UMFPACKdir) $(SRCdir) $(METISdir) $(AMDdir) $(CSPARSEdir) $(TRIANGLEdir) $(TETGENdir) $(SUPERLU_DISTdir)


# %-------------------------------------------------------%
# | SECTION 3: LIBRARIES                                  |
# |                                                       |
# | The following section defines the libraries that will |
# | be created and/or linked with when the libraries are  | 
# | being created or linked with.                         |
# %-------------------------------------------------------%
#
# Note: if vendor supplied BLAS and LAPACK libraries leave the
# libraries blank. You have to get your own copy of the tcl/tk 
# library!! 
#
# Note: For libraries that will be created (any in DIRS above)
# make sure the directory exsists where you want the library to go!

FE_LIBRARY      = $(libpath)/libOpenSees.a
NDARRAY_LIBRARY = $(libpath)/libndarray.a # BJ_UCD jeremic@ucdavis.edu
MATMOD_LIBRARY  = $(libpath)/libmatmod.a  # BJ_UCD jeremic@ucdavis.edu
BJMISC_LIBRARY  = $(libpath)/libBJmisc.a  # BJ_UCD jeremic@ucdavis.edu
LAPACK_LIBRARY  = $(libpath)/libLapack.a
BLAS_LIBRARY    = $(libpath)/libBlas.a
SUPERLU_LIBRARY = $(libpath)/libSuperLU.a
CBLAS_LIBRARY   = $(libpath)/libCBlas.a
ARPACK_LIBRARY  = $(libpath)/libArpack.a
UMFPACK_LIBRARY = $(libpath)/libUmfpack.a
ITPACK_LIBRARY = $(libpath)/libItpack.a
AMD_LIBRARY     = $(libpath)/libAMD.a
CSPARSE_LIBRARY = $(libpath)/libcsparse.a
TRIANGLE_LIBRARY = $(libpath)/libTriangle.a
TETGEN_LIBRARY = $(libpath)/libTetgen.a
RELIABILITY_LIBRARY = $(libpath)/libReliability.a
OPTIMIZATION_LIBRARY = $(libpath)/libOptimization.a

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)
    DISTRIBUTED_SUPERLU_LIBRARY = 
    METIS_LIBRARY   = 
else
    DISTRIBUTED_SUPERLU_LIBRARY = $(libpath)/libDistributedSuperLU.a 
    METIS_LIBRARY   = $(libpath)/libMetis.a
endif

TCL_LIBRARY = -ltcl -ltk

GRAPHIC_LIBRARY     =  -lXft -lXrender -lGLU -lGL -lX11

# WATCH OUT .. These libraries are removed when 'make wipe' is invoked.
WIPE_LIBS	= $(FE_LIBRARY) \
		$(LAPACK_LIBRARY) \
		$(BLAS_LIBRARY) \
		$(CBLAS_LIBRARY) \
		$(SUPERLU_LIBRARY) \
                $(DISTRIBUTED_SUPERLU_LIBRARY) \
		$(ARPACK_LIBRARY) \
		$(UMFPACK_LIBRARY) \
		$(ITPACK_LIBRARY) \
	        $(METIS_LIBRARY) \
	        $(AMD_LIBRARY) \
	        $(CSPARSE_LIBRARY) \
		$(TRIANGLE_LIBRARY) \
		$(TETGEN_LIBRARY) \
		$(RELIABILITY_LIBRARY)\
		$(OPTIMIZATION_LIBRARY)

# %---------------------------------------------------------%
# | SECTION 4: COMPILERS                                    |
# |                                                         |
# | The following macros specify compilers, linker/loaders, |
# | the archiver, and their options.  You need to make sure |
# | these are correct for your system.                      |
# %---------------------------------------------------------%

# Compilers


ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)

MPI_BIN = 
MPI_INCLUDE = 
MPI_LIB = 

CC++	= g++
CC      = gcc
FC	= gfortran

else

MPI_BIN = $(mpidir)/bin
MPI_INCLUDE = -I$(mpidir)/include
MPI_LIB = $(mpidir)/lib


CC++            =  $(MPI_BIN)/mpicxx
CC              =  $(MPI_BIN)/mpicc
FC              =  $(MPI_BIN)/mpif90
F90             =  $(MPI_BIN)/mpif90
FORTRAN             =  $(FC)

endif

AR		= ar 
ARFLAGS		= cqls
RANLIB		= ranlib
RANLIBFLAGS     =

# Compiler Flags
#
# NOTES:
#    C++ FLAGS TAKE need _UNIX or _WIN32 for preprocessor dircetives
#         - the _WIN32 for the Windows95/98 or NT operating system.
#    C FLAGS used -DUSE_VENDOR_BLAS (needed in SuperLU) if UNIX in C++ FLAGS
#

# modified as optimizaton currently causing problems with Steeln01 code
ifeq ($(DEBUG_MODE), DEBUG)




C++FLAGS         = -Wall -D_LINUX -D_UNIX -D_PYTHON3 -D_TCL85 $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) -D_COROTATIONAL $(PFEM_FLAG) $(ITPACK_FLAG) -g -pg $(MUMPS_FLAG) -fPIC
	      

CFLAGS          = -Wall -pg $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) $(PFEM_FLAG) -fPIC 
FFLAGS          = -Wall -fPIC -ffixed-line-length-none

# Linker
LINKER          = $(CC++)
LINKFLAGS       = -g -pg


else

C++FLAGS         = -Wall -D_LINUX -D_UNIX -D_PYTHON3 -D_TCL85 $(GRAPHIC_FLAG) $(RELIABILITY_FLAG) $(DEBUG_FLAG) $(PROGRAMMING_FLAG) -O3 -ffloat-store -D_COROTATIONAL $(PFEM_FLAG) $(MUMPS_FLAG) $(ITPACK_FLAG) -fPIC 
CFLAGS          = -Wall -O2 $(PFEM_FLAG) -fPIC
FFLAGS          = -Wall -O -fPIC -ffixed-line-length-none 

# Linker
LINKER          = $(CC++)
LINKFLAGS       = -rdynamic -Wl
LINKFLAGS = -rdynamic 
endif


# Misc
MAKE		= make
CD              = cd
ECHO            = echo
RM              = rm
RMFLAGS         = -f
SHELL           = /bin/sh

# %---------------------------------------------------------%
# | SECTION 5: COMPILATION                                  |
# |                                                         |
# | The following macros specify the macros used in         |
# | to compile the source code into object code.            |
# %---------------------------------------------------------%

.SUFFIXES:
.SUFFIXES:	.C .c .f .f90 .cpp .o .cpp

#
# %------------------%
# | Default command. |
# %------------------%
#
.DEFAULT:
	@$(ECHO) "Unknown target $@, try:  make help"
#
# %-------------------------------------------%
# |  Command to build .o files from .f files. |
# %-------------------------------------------%
#

.cpp.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(C++FLAGS) $(INCLUDES) -c $< -o $@

.C.o:
	@$(ECHO) Making $@ from $<
	$(CC++) $(C++FLAGS) $(INCLUDES) -c $< -o $@
.c.o:
	@$(ECHO) Making $@ from $<
	$(CC) $(CFLAGS) -c $< -o $@
.f.o:      
	@$(ECHO) Making $@ from $<
	$(FC) $(FFLAGS) -c $< -o $@

# %---------------------------------------------------------%
# | SECTION 6: OTHER LIBRARIES                              |
# |                                                         |
# | The following macros specify other libraries that must  |
# | be linked with when creating executables. These are     |
# | platform specific and typically order does matter!!     |
# %---------------------------------------------------------%

ifeq ($(PROGRAMMING_MODE), SEQUENTIAL)

MUMPS_LIB = 
MUMPS_INCLUDE = 

else

MUMPS_LIB = -L$(mumpsdir)/lib \
          -L$(scalapackdir)/lib \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsSOE.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsSolver.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSOE.o \
	$(FE)/system_of_eqn/linearSOE/mumps/MumpsParallelSolver.o \
	-ldmumps -lmumps_common \
	-lpord \
        -lscalapack -lblas -llapack

MUMPS_INCLUDE = -I$(mumpsdir)/include

endif

MACHINE_LINKLIBS  =  -L/usr/lib64 -L/lib64 -L/lib -L/usr/lib

MACHINE_NUMERICAL_LIBS  = $(RELIABILITY_LIBRARY) $(OPTIMIZATION_LIBRARY) -lm -lquadmath \
		$(ARPACK_LIBRARY) \
		$(SUPERLU_LIBRARY) \
		$(UMFPACK_LIBRARY) \
                $(DISTRIBUTED_SUPERLU_LIBRARY) \
                $(METIS_LIBRARY) \
		$(ITPACK_LIBRARY) \
		$(AMD_LIBRARY) \
		$(CSPARSE_LIBRARY) \
		$(TRIANGLE_LIBRARY) \
		$(TETGEN_LIBRARY) \
		$(LAPACK_LIBRARY) $(BLAS_LIBRARY) $(CBLAS_LIBRARY) \
		$(GRAPHIC_LIBRARY) \
		-ldl -lpng -lssl -lgfortran

MACHINE_SPECIFIC_LIBS = 

PARALLEL_LIB = $(MUMPS_LIB) -L$(MPI_LIB) -L$(minjie)/PARALLEL_NUMERICAL_LIBS/mpich-install/lib

# %---------------------------------------------------------%
# | SECTION 7: INCLUDE FILES                                |
# |                                                         |
# | The following macros specify include files needed for   |
# | compilation.                                            |
# %---------------------------------------------------------%
MACHINE_INCLUDES        = -I/usr/include \
			  -I/usr/local/include \
			  -I/usr/include/cxx \
			  -I/usr/include/python3.10



# this file contains all the OpenSees/SRC includes
include $(FE)/Makefile.incl

TCL_INCLUDES = -I/usr/include/tcl8.6

INCLUDES = $(TCL_INCLUDES) $(FE_INCLUDES) $(MACHINE_INCLUDES) $(SUPERLU_INCLUDES) $(MUMPS_INCLUDE) $(MPI_INCLUDE)








