"""
Tests for the NEW CatenaryCable element (6-DOF per node).

This file is meant to be run with the *new* OpenSees build (locally compiled)
which supersedes the old implementation.  It validates the element against:

1. **Analytical solution** — the known verification example from
   Salehi Ahmad Abad et al. (2013) / OpenSeesWiki (x=30 case).
   Node-2 displacements should be (8.58693, 0, 2.82578).

2. **Old implementation reference** — compares against the results previously
   saved by ``generate_catenary_reference.py`` (run with the old
   OpenSeesPy from ``~/engineering-venv``).

3. **Self-weight equilibrium** — a simple sanity check that the vertical
   reactions sum to the total self-weight.

References:
    Salehi Ahmad Abad, M., Shooshtari, A., Esmaeili, V., & Naghavi Riabi, A. (2013).
    Nonlinear analysis of cable structures under general loadings.
    Finite Elements in Analysis and Design, 73, 11–19.
    https://doi.org/10.1016/j.finel.2013.05.002

    OpenSeesWiki — CatenaryCableElement:
    https://opensees.berkeley.edu/wiki/index.php/CatenaryCableElement
"""

import json
import math
import pathlib

try:
    import opensees as ops
except ModuleNotFoundError:
    import openseespy.opensees as ops

# ---------------------------------------------------------------------------
#  Path for the reference JSON file (generated by
#  ``generate_catenary_reference.py`` on the old OpenSeesPy)
# ---------------------------------------------------------------------------
_REFERENCE_FILE = pathlib.Path(__file__).resolve().parent / "catenary_reference.json"


# ===========================================================================
#  Helpers
# ===========================================================================

def _build_verification_model(ndf=3):
    """
    Build the 3-node, 2-element catenary model from the OpenSeesWiki example
    (Salehi Ahmad Abad 2013, x=30 case).

    Parameters
    ----------
    ndf : int
        Number of DOFs per node (3 for old, 6 for new).
    """
    ops.wipe()
    ops.model("basic", "-ndm", 3, "-ndf", ndf)

    x = 30.0
    ops.node(1, 0.0, 0.0, 90.0)
    ops.node(2, x / 2, 0.0, 40.0)
    ops.node(3, x, 60.0, 30.0)

    if ndf == 3:
        ops.fix(1, 1, 1, 1)
        ops.fix(2, 0, 1, 0)
        ops.fix(3, 1, 1, 1)
    else:
        ops.fix(1, 1, 1, 1, 1, 1, 1)
        ops.fix(2, 0, 1, 0, 1, 1, 1)
        ops.fix(3, 1, 1, 1, 1, 1, 1)

    w3 = -0.00001
    E = 3.0e7
    A = 1.0
    L0_total = 100.0
    alpha = 6.5e-6
    temperature_change = 100.0
    rho = w3 / 9.81
    error_tol = 1e-6
    N_substeps = 20
    mass_type = 0

    ops.element("CatenaryCable", 1, 1, 2,
                w3, E, A, L0_total / 2, alpha, temperature_change, rho,
                error_tol, N_substeps, mass_type)
    ops.element("CatenaryCable", 2, 2, 3,
                w3, E, A, L0_total / 2, alpha, temperature_change, rho,
                error_tol, N_substeps, mass_type)

    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 2, 1)
    ops.eleLoad("-ele", 1, 2, "-type", "-beamUniform", 0.0, 0.0, -1.0)

    ops.system("Diagonal")  # Avoid MKL sparse solver
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-5, 100, 1)
    ops.integrator("LoadControl", 1.0 / 10)
    ops.algorithm("Newton")
    ops.analysis("Static")
    ops.analyze(10)


def _get_element_forces(ele_tags):
    """Return {tag: [forces]} for each element tag."""
    return {str(tag): [float(v) for v in ops.eleForce(tag)] for tag in ele_tags}


def _get_node_displacements(node_tags, ndof=3):
    """Return {tag: [disp]} for each node tag."""
    return {str(tag): [ops.nodeDisp(tag, i + 1) for i in range(ndof)]
            for tag in node_tags}


# ===========================================================================
#  Tests
# ===========================================================================

# ---- Analytical solution (displacements) ---------------------------------

def test_analytical_displacements_3dof():
    """
    NEW implementation with 3-DOF nodes — should match the known
    analytical values from Salehi Ahmad Abad (2013).

    Expected Node-2 disp: (8.58693, 0.00000, 2.82578)
    """
    _build_verification_model(ndf=3)
    d2 = [ops.nodeDisp(2, i + 1) for i in range(3)]

    expected = (8.58693, 0.0, 2.82578)
    for got, exp in zip(d2, expected):
        assert math.isclose(got, exp, abs_tol=1e-4), (
            f"Node-2 disp (3-DOF new): got {got}, expected {exp}"
        )


def test_analytical_displacements_6dof():
    """
    NEW implementation with 6-DOF per node (12 total element DOFs) —
    must produce the SAME translational displacements as the 3-DOF case.

    Expected Node-2 disp: (8.58693, 0.00000, 2.82578)
    """
    _build_verification_model(ndf=6)
    d2 = [ops.nodeDisp(2, i + 1) for i in range(3)]

    expected = (8.58693, 0.0, 2.82578)
    for got, exp in zip(d2, expected):
        assert math.isclose(got, exp, abs_tol=1e-4), (
            f"Node-2 disp (6-DOF new): got {got}, expected {exp}"
        )


# ---- Comparison with old reference ---------------------------------------

def test_against_old_reference_displacements():
    """
    Compare node displacements from the NEW implementation against the
    reference file generated by the old OpenSeesPy CatenaryCable.
    """
    _build_verification_model(ndf=3)
    new_disp = _get_node_displacements([1, 2, 3], ndof=3)

    assert _REFERENCE_FILE.exists(), (
        f"Reference file {_REFERENCE_FILE} not found. "
        "Run 'python tests/generate_catenary_reference.py' from the "
        "~/engineering-venv first."
    )
    with open(_REFERENCE_FILE) as fh:
        ref = json.load(fh)
    old_disp = ref["node_displacements"]

    for tag in ("1", "2", "3"):
        for i in range(3):
            assert math.isclose(new_disp[tag][i], old_disp[tag][i],
                                abs_tol=1e-4), (
                f"Node-{tag} displacement component {i} mismatch: "
                f"new={new_disp[tag][i]}, old={old_disp[tag][i]}"
            )


def test_against_old_reference_forces():
    """
    Compare element end-forces from the NEW implementation against the
    reference file generated by the old OpenSeesPy CatenaryCable.

    Note: new 3-DOF case produces 6-component force vectors (same as old);
          new 6-DOF case produces 12-component vectors (only the
          translational components should match).
    """
    # --- 3-DOF comparison ---
    _build_verification_model(ndf=3)
    new_forces_3 = _get_element_forces([1, 2])

    with open(_REFERENCE_FILE) as fh:
        ref = json.load(fh)
    old_forces = ref["element_forces"]

    for tag in ("1", "2"):
        for i in range(6):
            assert math.isclose(new_forces_3[tag][i], old_forces[tag][i],
                                abs_tol=1e-4), (
                f"Element {tag} force component {i} mismatch (3-DOF): "
                f"new={new_forces_3[tag][i]}, old={old_forces[tag][i]}"
            )

    # --- 6-DOF comparison (translational components only) ---
    _build_verification_model(ndf=6)
    new_forces_6 = _get_element_forces([1, 2])

    for tag in ("1", "2"):
        # Node-i translations  (indices 0,1,2 in 12-DOF)
        for i in range(3):
            assert math.isclose(new_forces_6[tag][i], old_forces[tag][i],
                                abs_tol=1e-4), (
                f"Element {tag} node-i force component {i} mismatch (6-DOF): "
                f"new={new_forces_6[tag][i]}, old={old_forces[tag][i]}"
            )
        # Node-j translations  (indices 6,7,8 in 12-DOF ↔ 3,4,5 in 6-DOF)
        for i in range(3):
            assert math.isclose(new_forces_6[tag][6 + i], old_forces[tag][3 + i],
                                abs_tol=1e-4), (
                f"Element {tag} node-j force component {i} mismatch (6-DOF): "
                f"new={new_forces_6[tag][6 + i]}, old={old_forces[tag][3 + i]}"
            )
        # Rotational DOFs must be zero
        for i in (3, 4, 5, 9, 10, 11):
            assert math.isclose(new_forces_6[tag][i], 0.0, abs_tol=1e-15), (
                f"Element {tag} rotational DOF {i} is non-zero: "
                f"{new_forces_6[tag][i]}"
            )


# ---- Self-weight equilibrium (physics sanity check) ----------------------

def test_self_weight_only_3dof():
    """
    3-DOF: self-weight only (no eleLoad). Vertical reactions must sum
    to total self-weight, each support carries half, horizontal reactions
    cancel.
    """
    ops.wipe()
    ops.model("basic", "-ndm", 3, "-ndf", 3)

    L_span = 100.0
    w = -10.0            # N/m

    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, L_span, 0.0, 0.0)
    ops.fix(1, 1, 1, 1)
    ops.fix(2, 1, 1, 1)

    E = 2.0e11
    A = 1.0e-3
    L0 = 102.0
    alpha = 0.0
    dT = 0.0
    rho = abs(w) / 9.81
    tol = 1e-8
    Nsub = 10

    ops.element("CatenaryCable", 1, 1, 2,
                w, E, A, L0, alpha, dT, rho, tol, Nsub, 0)

    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 1, 1)

    ops.system("Diagonal")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-5, 100)
    ops.integrator("LoadControl", 0.1)
    ops.algorithm("Newton")
    ops.analysis("Static")
    ops.analyze(10)

    ops.reactions()

    total_weight = abs(w) * L0
    R1z = ops.nodeReaction(1, 3)
    R2z = ops.nodeReaction(2, 3)

    assert math.isclose(R1z + R2z, total_weight, rel_tol=1e-3), (
        f"Sum of vertical reactions ({R1z + R2z}) != total weight ({total_weight})"
    )
    assert math.isclose(R1z, total_weight / 2, rel_tol=5e-2), (
        f"R1z = {R1z}, expected ~{total_weight / 2}"
    )
    assert math.isclose(R2z, total_weight / 2, rel_tol=5e-2), (
        f"R2z = {R2z}, expected ~{total_weight / 2}"
    )

    R1x = ops.nodeReaction(1, 1)
    R2x = ops.nodeReaction(2, 1)
    assert math.isclose(R1x + R2x, 0.0, abs_tol=1e-6), (
        f"Horizontal reactions don't cancel: {R1x} + {R2x} = {R1x + R2x}"
    )


def test_self_weight_plus_eleload_3dof():
    """
    3-DOF: self-weight + eleLoad. Vertical reactions must sum to
    (|w| + |eleLoad|) * L0, verifying that addLoad() accumulates
    rather than overwrites the self-weight.
    """
    ops.wipe()
    ops.model("basic", "-ndm", 3, "-ndf", 3)

    L_span = 100.0
    w = -10.0            # N/m self-weight
    eleload_z = -1.0     # N/m additional load

    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, L_span, 0.0, 0.0)
    ops.fix(1, 1, 1, 1)
    ops.fix(2, 1, 1, 1)

    E = 2.0e11
    A = 1.0e-3
    L0 = 102.0
    alpha = 0.0
    dT = 0.0
    rho = abs(w) / 9.81
    tol = 1e-8
    Nsub = 10

    ops.element("CatenaryCable", 1, 1, 2,
                w, E, A, L0, alpha, dT, rho, tol, Nsub, 0)

    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 1, 1)
    ops.eleLoad("-ele", 1, "-type", "-beamUniform", 0.0, 0.0, eleload_z)

    ops.system("Diagonal")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-5, 100)
    ops.integrator("LoadControl", 0.1)
    ops.algorithm("Newton")
    ops.analysis("Static")
    ops.analyze(10)

    ops.reactions()

    total_load = (abs(w) + abs(eleload_z)) * L0
    R1z = ops.nodeReaction(1, 3)
    R2z = ops.nodeReaction(2, 3)

    assert math.isclose(R1z + R2z, total_load, rel_tol=1e-3), (
        f"Sum of vertical reactions ({R1z + R2z}) != total load ({total_load})"
    )
    assert math.isclose(R1z, total_load / 2, rel_tol=5e-2), (
        f"R1z = {R1z}, expected ~{total_load / 2}"
    )
    assert math.isclose(R2z, total_load / 2, rel_tol=5e-2), (
        f"R2z = {R2z}, expected ~{total_load / 2}"
    )

    R1x = ops.nodeReaction(1, 1)
    R2x = ops.nodeReaction(2, 1)
    assert math.isclose(R1x + R2x, 0.0, abs_tol=1e-6), (
        f"Horizontal reactions don't cancel: {R1x} + {R2x} = {R1x + R2x}"
    )


def test_self_weight_only_6dof():
    """
    6-DOF: self-weight only (no eleLoad). Translational reactions must
    match the 3-DOF case, and no spurious moment reactions appear.
    """
    ops.wipe()
    ops.model("basic", "-ndm", 3, "-ndf", 6)

    L_span = 100.0
    w = -10.0

    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, L_span, 0.0, 0.0)
    ops.fix(1, 1, 1, 1, 1, 1, 1)
    ops.fix(2, 1, 1, 1, 1, 1, 1)

    E = 2.0e11
    A = 1.0e-3
    L0 = 102.0
    alpha = 0.0
    dT = 0.0
    rho = abs(w) / 9.81
    tol = 1e-8
    Nsub = 10

    ops.element("CatenaryCable", 1, 1, 2,
                w, E, A, L0, alpha, dT, rho, tol, Nsub, 0)

    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 1, 1)

    ops.system("Diagonal")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-5, 100)
    ops.integrator("LoadControl", 0.1)
    ops.algorithm("Newton")
    ops.analysis("Static")
    ops.analyze(10)

    ops.reactions()

    total_weight = abs(w) * L0
    R1z = ops.nodeReaction(1, 3)
    R2z = ops.nodeReaction(2, 3)

    assert math.isclose(R1z + R2z, total_weight, rel_tol=1e-3), (
        f"Sum of vert reactions ({R1z + R2z}) != total weight ({total_weight})"
    )
    assert math.isclose(R1z, total_weight / 2, rel_tol=5e-2), (
        f"R1z = {R1z}, expected ~{total_weight / 2}"
    )
    assert math.isclose(R2z, total_weight / 2, rel_tol=5e-2), (
        f"R2z = {R2z}, expected ~{total_weight / 2}"
    )

    R1x = ops.nodeReaction(1, 1)
    R2x = ops.nodeReaction(2, 1)
    assert math.isclose(R1x + R2x, 0.0, abs_tol=1e-6)

    # No spurious moment reactions at the fixed supports
    for node in (1, 2):
        for dof in (4, 5, 6):
            assert math.isclose(ops.nodeReaction(node, dof), 0.0,
                                abs_tol=1e-10), (
                f"Node {node} reaction DOF {dof} is non-zero: "
                f"{ops.nodeReaction(node, dof)}"
            )


def test_self_weight_plus_eleload_6dof():
    """
    6-DOF: self-weight + eleLoad. Translational reactions must sum to
    (|w| + |eleLoad|) * L0, and no spurious moment reactions appear.
    """
    ops.wipe()
    ops.model("basic", "-ndm", 3, "-ndf", 6)

    L_span = 100.0
    w = -10.0
    eleload_z = -1.0

    ops.node(1, 0.0, 0.0, 0.0)
    ops.node(2, L_span, 0.0, 0.0)
    ops.fix(1, 1, 1, 1, 1, 1, 1)
    ops.fix(2, 1, 1, 1, 1, 1, 1)

    E = 2.0e11
    A = 1.0e-3
    L0 = 102.0
    alpha = 0.0
    dT = 0.0
    rho = abs(w) / 9.81
    tol = 1e-8
    Nsub = 10

    ops.element("CatenaryCable", 1, 1, 2,
                w, E, A, L0, alpha, dT, rho, tol, Nsub, 0)

    ops.timeSeries("Linear", 1)
    ops.pattern("Plain", 1, 1)
    ops.eleLoad("-ele", 1, "-type", "-beamUniform", 0.0, 0.0, eleload_z)

    ops.system("Diagonal")
    ops.constraints("Plain")
    ops.numberer("Plain")
    ops.test("NormDispIncr", 1.0e-5, 100)
    ops.integrator("LoadControl", 0.1)
    ops.algorithm("Newton")
    ops.analysis("Static")
    ops.analyze(10)

    ops.reactions()

    total_load = (abs(w) + abs(eleload_z)) * L0
    R1z = ops.nodeReaction(1, 3)
    R2z = ops.nodeReaction(2, 3)

    assert math.isclose(R1z + R2z, total_load, rel_tol=1e-3), (
        f"Sum of vert reactions ({R1z + R2z}) != total load ({total_load})"
    )
    assert math.isclose(R1z, total_load / 2, rel_tol=5e-2), (
        f"R1z = {R1z}, expected ~{total_load / 2}"
    )
    assert math.isclose(R2z, total_load / 2, rel_tol=5e-2), (
        f"R2z = {R2z}, expected ~{total_load / 2}"
    )

    R1x = ops.nodeReaction(1, 1)
    R2x = ops.nodeReaction(2, 1)
    assert math.isclose(R1x + R2x, 0.0, abs_tol=1e-6)

    # No spurious moment reactions at the fixed supports
    for node in (1, 2):
        for dof in (4, 5, 6):
            assert math.isclose(ops.nodeReaction(node, dof), 0.0,
                                abs_tol=1e-10), (
                f"Node {node} reaction DOF {dof} is non-zero: "
                f"{ops.nodeReaction(node, dof)}"
            )


# ===========================================================================
#  Entry point
# ===========================================================================
if __name__ == "__main__":
    import sys
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))