; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26129.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\iMeG\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
