#!/bin/bash               
#$ -V                     # Inherit the submission environment
#$ -cwd                   # Start job in  submission directory
#$ -N testMP               # Job Name
#$ -j y                   # combine stderr & stdout into stdout    
#$ -o $JOB_NAME.o$JOB_ID  # Name of the output file (eg. myMPI.oJobID)
#$ -pe 16way 32           # Requests 16 cores/node, 32 cores total
#$ -q normal              # Queue name
#$ -l h_rt=01:00:00       # Run time (hh:mm:ss) - 1.5 hours
## -M fmckenna@ce.berkeley.edu      # Email notification address (UNCOMMENT)
## -m be                  # Email at Begin/End of job  (UNCOMMENT)
 set -x                   #{echo cmds, use "set echo" in csh}
 ibrun OpenSeesMP Example.tcl            # Run the MPI executable named "a.out"
