clear;
close all;
clc;
hfig = figure;
set(hfig,'Color', [1,1,1],...
         'PaperPositionMode','auto',...
         'InvertHardcopy','off');
axes('Xlim',[-0.2 [expr *1.1] ],'Ylim',[-0.2 [expr *1.1]], 'Visible','off');
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line(x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
x = [];
y = [];
line (x,y,'Color','b','LineWidth',2.0);
