
OBJS_COMMON_MOD = \
        ana_omp_m.o\
        ana_blk_m.o\
        ana_orderings_wrappers_m.o\
        double_linked_list.o\
        fac_asm_build_sort_index_ELT_m.o\
        fac_asm_build_sort_index_m.o\
        fac_descband_data_m.o\
        fac_future_niv2_mod.o\
        fac_ibct_data_m.o\
        fac_maprow_data_m.o\
        front_data_mgt_m.o\
        lr_common.o \
        mumps_comm_ibcast.o\
        mumps_l0_omp_m.o\
        mumps_memory_mod.o\
        mumps_mpitoomp_m.o\
        mumps_ooc_common.o\
        mumps_static_mapping.o\
        omp_tps_common_m.o

OBJS_COMMON_OTHER = \
        ana_blk.o\
        ana_orderings.o\
        ana_set_ordering.o\
        ana_AMDMF.o\
        bcast_errors.o\
        estim_flops.o\
        mumps_type_size.o \
        mumps_type2_blocking.o \
        mumps_version.o \
        mumps_print_defined.o \
        mumps_common.o\
        mumps_pord.o\
        mumps_metis.o\
        mumps_metis64.o\
        mumps_metis_int.o\
        mumps_scotch.o\
        mumps_scotch64.o\
        mumps_scotch_int.o\
        mumps_size.o\
        mumps_io.o\
        mumps_io_basic.o\
        mumps_io_thread.o\
        mumps_io_err.o\
        mumps_numa.o \
        mumps_thread.o \
        mumps_save_restore_C.o \
        mumps_config_file_C.o \
        mumps_thread_affinity.o \
        mumps_register_thread.o \
        tools_common.o \
        sol_common.o

OBJS_MOD =   \
        dana_aux.o \
        dana_aux_par.o \
        dana_lr.o\
        dfac_asm_master_ELT_m.o\
        dfac_asm_master_m.o\
        dfac_front_aux.o\
        dfac_front_LU_type1.o\
        dfac_front_LU_type2.o\
        dfac_front_LDLT_type1.o\
        dfac_front_LDLT_type2.o\
        dfac_front_type2_aux.o\
        dfac_sispointers_m.o\
        dfac_lr.o\
        dfac_mem_dynamic.o\
        dfac_omp_m.o\
        dfac_par_m.o\
        dfac_sol_l0omp_m.o\
        dlr_core.o\
        dlr_stats.o\
        dlr_type.o\
        dmumps_comm_buffer.o\
        dmumps_config_file.o\
        dmumps_load.o\
        dmumps_lr_data_m.o\
        dmumps_ooc_buffer.o\
        dmumps_ooc.o\
        dmumps_sol_es.o\
        dmumps_save_restore.o\
        dmumps_save_restore_files.o\
        dmumps_struc_def.o\
        domp_tps_m.o\
        dsol_lr.o\
        dsol_omp_m.o\
        dstatic_ptr_m.o

OBJS_OTHER = \
        dini_driver.o\
        dana_driver.o\
        dfac_driver.o\
        dsol_driver.o\
        dsol_distrhs.o\
        dend_driver.o\
        dana_aux_ELT.o\
        dana_dist_m.o\
        dana_LDLT_preprocess.o\
        dana_reordertree.o\
        darrowheads.o\
        dbcast_int.o\
        dfac_asm_ELT.o\
        dfac_asm.o\
        dfac_b.o\
        dfac_distrib_distentry.o\
        dfac_distrib_ELT.o\
        dfac_lastrtnelind.o\
        dfac_mem_alloc_cb.o\
        dfac_mem_compress_cb.o\
        dfac_mem_free_block_cb.o\
        dfac_mem_stack_aux.o\
        dfac_mem_stack.o\
        dfac_process_band.o\
        dfac_process_blfac_slave.o\
        dfac_process_blocfacto_LDLT.o\
        dfac_process_blocfacto.o\
        dfac_process_bf.o\
        dfac_process_end_facto_slave.o\
        dfac_process_contrib_type1.o\
        dfac_process_contrib_type2.o\
        dfac_process_contrib_type3.o\
        dfac_process_maprow.o\
        dfac_process_master2.o\
        dfac_process_message.o\
        dfac_process_root2slave.o\
        dfac_process_root2son.o\
        dfac_process_rtnelind.o\
        dfac_root_parallel.o\
        dfac_scalings.o\
        dfac_determinant.o\
        dfac_scalings_simScaleAbs.o\
        dfac_scalings_simScale_util.o\
        dfac_sol_pool.o\
        dfac_type3_symmetrize.o\
        dini_defaults.o\
        dmumps_c.o\
        dmumps_driver.o\
        dmumps_f77.o\
        dmumps_gpu.o\
        dmumps_iXamax.o\
        dana_mtrans.o\
        dooc_panel_piv.o\
        drank_revealing.o\
        dsol_aux.o\
        dsol_bwd_aux.o\
        dsol_bwd.o\
        dsol_c.o\
        dsol_fwd_aux.o\
        dsol_fwd.o\
        dsol_matvec.o\
        dsol_root_parallel.o\
        dtools.o\
        dtype3_root.o


