set (PETSC_HAVE_BLASLAPACK YES)
set (PETSC_HAVE_MATHLIB YES)
set (PETSC_HAVE_PTHREAD YES)
set (PETSC_HAVE_SCHED_CPU_SET_T 1)
set (PETSC_HAVE_PTHREAD_BARRIER_T 1)
set (PETSC_HAVE_SYS_SYSCTL_H 1)
set (PETSC_HAVE_MPI YES)
set (PETSC_HAVE_MPI_F90MODULE YES)
set (PETSC_HAVE_MPI_WIN_CREATE_FEATURE YES)
set (PETSC_HAVE_MPI_IALLREDUCE YES)
set (PETSC_HAVE_OMPI_MINOR_VERSION 0)
set (PETSC_HAVE_MPI_REDUCE_SCATTER_BLOCK YES)
set (PETSC_HAVE_MPI_IN_PLACE YES)
set (PETSC_HAVE_MPI_COMM_C2F YES)
set (PETSC_HAVE_MPI_GET_LIBRARY_VERSION YES)
set (PETSC_HAVE_MPI_SHARED_COMM YES)
set (PETSC_HAVE_MPI_INT64_T YES)
set (PETSC_HAVE_MPI_TYPE_GET_EXTENT YES)
set (PETSC_HAVE_MPI_WIN_CREATE YES)
set (PETSC_HAVE_MPIIO YES)
set (PETSC_HAVE_MPI_INIT_THREAD YES)
set (PETSC_HAVE_MPI_COMBINER_NAMED YES)
set (PETSC_HAVE_MPI_LONG_DOUBLE YES)
set (PETSC_HAVE_MPI_COMM_F2C YES)
set (PETSC_HAVE_MPI_PROCESS_SHARED_MEMORY YES)
set (PETSC_HAVE_MPI_TYPE_GET_ENVELOPE YES)
set (PETSC_HAVE_OMPI_MAJOR_VERSION 4)
set (PETSC_HAVE_MPI_REDUCE_SCATTER YES)
set (PETSC_HAVE_MPI_COMBINER_DUP YES)
set (PETSC_HAVE_MPI_TYPE_DUP YES)
set (PETSC_HAVE_MPI_COMM_SPAWN YES)
set (PETSC_HAVE_MPI_FINT YES)
set (PETSC_HAVE_MPI_IBARRIER YES)
set (PETSC_HAVE_MPI_FINALIZED YES)
set (PETSC_HAVE_MPI_COMBINER_CONTIGUOUS YES)
set (PETSC_HAVE_MPI_WIN_SHARED_QUERY YES)
set (PETSC_HAVE_OMPI_RELEASE_VERSION 1)
set (PETSC_HAVE_MPI_REDUCE_LOCAL YES)
set (PETSC_HAVE_MPI_REPLACE YES)
set (PETSC_HAVE_MPI_EXSCAN YES)
set (PETSC_HAVE_MPI_C_DOUBLE_COMPLEX YES)
set (PETSC_HAVE_MPI_ALLTOALLW YES)
set (PETSC_HAVE_MPI_WIN_ALLOCATE_SHARED YES)
set (PETSC_HAVE_STRCASECMP YES)
set (PETSC_HAVE_GET_NPROCS YES)
set (PETSC_HAVE_POPEN YES)
set (PETSC_HAVE_SIGSET YES)
set (PETSC_HAVE_GETWD YES)
set (PETSC_HAVE_VSNPRINTF YES)
set (PETSC_HAVE_TIMES YES)
set (PETSC_HAVE_DLSYM YES)
set (PETSC_HAVE_SNPRINTF YES)
set (PETSC_HAVE_GETHOSTBYNAME YES)
set (PETSC_HAVE_GETCWD YES)
set (PETSC_HAVE_DLERROR YES)
set (PETSC_HAVE_FORK YES)
set (PETSC_HAVE_RAND YES)
set (PETSC_HAVE_GETTIMEOFDAY YES)
set (PETSC_HAVE_DLCLOSE YES)
set (PETSC_HAVE_UNAME YES)
set (PETSC_HAVE_GETHOSTNAME YES)
set (PETSC_HAVE_MKSTEMP YES)
set (PETSC_HAVE_SIGACTION YES)
set (PETSC_HAVE_DRAND48 YES)
set (PETSC_HAVE_MEMALIGN YES)
set (PETSC_HAVE_VA_COPY YES)
set (PETSC_HAVE_CLOCK YES)
set (PETSC_HAVE_ACCESS YES)
set (PETSC_HAVE_SIGNAL YES)
set (PETSC_HAVE_USLEEP YES)
set (PETSC_HAVE_GETRUSAGE YES)
set (PETSC_HAVE_VFPRINTF YES)
set (PETSC_HAVE_NANOSLEEP YES)
set (PETSC_HAVE_GETDOMAINNAME YES)
set (PETSC_HAVE_TIME YES)
set (PETSC_HAVE_LSEEK YES)
set (PETSC_HAVE_SOCKET YES)
set (PETSC_HAVE_SYSINFO YES)
set (PETSC_HAVE_READLINK YES)
set (PETSC_HAVE_REALPATH YES)
set (PETSC_HAVE_DLOPEN YES)
set (PETSC_HAVE_MEMMOVE YES)
set (PETSC_HAVE__GFORTRAN_IARGC YES)
set (PETSC_HAVE_MMAP YES)
set (PETSC_HAVE_GETPAGESIZE YES)
set (PETSC_HAVE_SLEEP YES)
set (PETSC_HAVE_VPRINTF YES)
set (PETSC_HAVE_BZERO YES)
set (PETSC_SIGNAL_CAST  )
set (PETSC_USE_SOCKET_VIEWER 1)
set (PETSC_USE_ISATTY YES)
set (PETSC_USE_SINGLE_LIBRARY 1)
set (PETSC_USE_INFO YES)
set (PETSC_USE_BACKWARD_LOOP 1)
set (PETSC_USE_MALLOC_COALESCED YES)
set (PETSC_USE_LOG YES)
set (PETSC_USE_CTABLE 1)
set (PETSC_USE_COMPLEX NO)
set (PETSC_USE_REAL_DOUBLE YES)
set (PETSC_CLANGUAGE_C YES)
set (PETSC_HAVE_FORTRAN YES)
set (PETSC_USING_F90 YES)
set (PETSC_USING_F2003 YES)
set (PETSC_HAVE_CXX YES)
set (BUILD_SHARED_LIBS YES)
find_library (PETSC_LAPACK_LIB lapack HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_BLAS_LIB blas HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_MPI_USEMPIF08_LIB mpi_usempif08 HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_MPI_USEMPI_IGNORE_TKR_LIB mpi_usempi_ignore_tkr HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_MPI_MPIFH_LIB mpi_mpifh HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_MPI_LIB mpi HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_GFORTRAN_LIB gfortran HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_M_LIB m HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_GCC_S_LIB gcc_s HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_QUADMATH_LIB quadmath HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_PTHREAD_LIB pthread HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_STDC++_LIB stdc++ HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
find_library (PETSC_DL_LIB dl HINTS "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib/gcc/x86_64-unknown-linux-gnu/5.5.0" "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.5.0_4/lib" "/lib/x86_64-linux-gnu" "/usr/lib/x86_64-linux-gnu" "/home/linuxbrew/.linuxbrew/lib" "/home/linuxbrew/.linuxbrew/opt/libevent/lib" "/home/linuxbrew/.linuxbrew/Cellar/open-mpi/4.0.1_1/lib" )
mark_as_advanced (PETSC_LAPACK_LIB PETSC_BLAS_LIB PETSC_MPI_USEMPIF08_LIB PETSC_MPI_USEMPI_IGNORE_TKR_LIB PETSC_MPI_MPIFH_LIB PETSC_MPI_LIB PETSC_GFORTRAN_LIB PETSC_M_LIB PETSC_GCC_S_LIB PETSC_QUADMATH_LIB PETSC_PTHREAD_LIB PETSC_STDC++_LIB PETSC_DL_LIB)
set (PETSC_PACKAGE_LIBS "${PETSC_LAPACK_LIB}" "${PETSC_BLAS_LIB}" "${PETSC_MPI_USEMPIF08_LIB}" "${PETSC_MPI_USEMPI_IGNORE_TKR_LIB}" "${PETSC_MPI_MPIFH_LIB}" "${PETSC_MPI_LIB}" "${PETSC_GFORTRAN_LIB}" "${PETSC_M_LIB}" "${PETSC_GCC_S_LIB}" "${PETSC_QUADMATH_LIB}" "${PETSC_PTHREAD_LIB}" "${PETSC_STDC++_LIB}" "${PETSC_DL_LIB}")
set (PETSC_PACKAGE_INCLUDES )
