name: Git Push Test
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on:
  push:
    paths:
      - ".github/workflows/git_push.yml"
  workflow_dispatch:

jobs:
  build:
    name: git push test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: File Make
        run: |
          cd build
          touch memo.txt
          ls -all
      - name: Git PR Create
        run: gh pr create -B "master" -t "CMake Build on Mac" -b ""
        env:
          GH_TOKEN: "${GITHUB_TOKEN}"
