name: CMake Build on Mac
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: workflow_dispatch

jobs:
  build:
    name: build on mac
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Install Library
        run: |
         ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
         brew install open-mpi
         pip3 install conan
      - name: Check Library
        run: |
          echo "puts [info tclversion]" | tclsh          
          cmake --version
          gfortran --version
          ompi_info | head
          python3 --version
          conan --version
      - name: Build
        run: |
          mkdir artifact
          mkdir build
          cd build
          conan install ..
          cmake -S .. -B ./
          cmake --build ./ --target OpenSees
          cmake --build ./ --target OpenSeesPy
          mv ./lib/OpenSeesPy.dylib ./lib/opensees.so
          cp ./lib/opensees.so ./../artifact
          cp ./bin/OpenSees ./../artifact
# Verification
      - name: Verification OpenSeesPySP
        run: |
          cd ./EXAMPLES/ExamplePython/
          export PYTHONPATH="../../build/lib/"
          python3 -c "import sys; print(sys.path)"
          python3 example_variable_analysis.py
# Save
      - uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ./artifact
