name: CMake Build on Mac
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: [push,workflow_dispatch]

jobs:
  build:
    name: build on mac
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Install Library
        run: |
         ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
         brew install open-mpi
         pip3 install conan
#         brew install gfortran
#         brew install cmake
#         brew install tcl8.6
#         brew install tk8.6
#         brew install python
      - name: Check Library
        run: |
          cmake --version
          gfortran --version
          python3 --version
          conan --version
      - name: Build
        run: |
          mkdir build
          cd build
          conan install ..
          cmake -S .. -B ./
          cmake --build ./ --target OpenSees
          cmake --build ./ --target OpenSeesPy
          mv lib/OpenSeesPy.dylib lib/opensees.so

# # Simple sanity test
#     - name: Verification OpenSeesPySP
#       run: |
#         cd ./build
#         cd ../EXAMPLES/ExamplePython/
#         export PYTHONPATH="../../build/lib/"
#         python -c "import sys; print(sys.path)"
#         python example_variable_analysis.py
