name: CMake Build on Mac
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: 
  push:
    paths:
      - ".github/workflows/mac_cmake.yml"
  workflow_dispatch:

jobs:
  build:
    name: build on mac
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
# Install and Check Library
      - name: Install Library
        run: |
         ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
         brew install open-mpi
         pip3 install conan
      - name: Check Library
        run: |
          echo "puts [info tclversion]" | tclsh          
          cmake --version
          gfortran --version
          ompi_info | head
          python3 --version
          conan --version
# Build
      - name: Build
        run: |
          mkdir artifact
          cd build
          conan install ..
          cmake -S .. -B ./
          cmake --build ./ --target OpenSees
          cmake --build ./ --target OpenSeesPy
          mv ./lib/OpenSeesPy.dylib ./lib/opensees.so
          cp ./lib/opensees.so ./../artifact
          cp ./bin/OpenSees ./../artifact
# Verification
      - name: Verification OpenSeesPySP
        run: |
          cd ./EXAMPLES/ExamplePython/
          export PYTHONPATH="../../build/lib/"
          python3 -c "import sys; print(sys.path)"
          python3 example_variable_analysis.py
# Push Diff
      - name: Push build Directory
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Push from CMake Build on Mac"
          git push origin HEAD:${GITHUB_REF}
# Save
      - uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ./artifact
