name: CMake Build on Mac
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: [push,workflow_dispatch]

jobs:
  build:
    name: build on mac
    runs-on: macos-12
    steps:
#       - uses: actions/checkout@v2
      - name: Install Library
        run: |
          ls -all /usr/local/bin
#          gfortran -v
#          brew install gfortran
#          brew install open-mpi
#          pip3 install conan
#      - name: Build
#        run: |
#          mkdir build
#          cd build
#          conan install ..
#          cmake -S .. -B ./
#          cmake --build ./ --target OpenSees
#          cmake --build ./ --target OpenSeesPy
#          mv lib/OpenSeesPy.dylib lib/opensees.so

# # Simple sanity test
#     - name: Verification OpenSeesPySP
#       run: |
#         cd ./build
#         cd ../EXAMPLES/ExamplePython/
#         export PYTHONPATH="../../build/lib/"
#         python -c "import sys; print(sys.path)"
#         python example_variable_analysis.py
