name: CMake Build on Mac
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: 
  push:
    paths:
      - ".github/workflows/mac_cmake.yml"
  workflow_dispatch:

jobs:
  build:
    name: build on mac
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0       
      - uses: actions/cache@v2
        with:
          path: |
            ~/.conan
            build
            /usr/local/Cellar/open-mpi/4.1.4
          key: ${{ runner.os }}
      - uses: chetan/git-restore-mtime-action@v1.0      
# Install and Check Library
      - name: Install Library
        run: |
         ln -s /usr/local/bin/gfortran-11 /usr/local/bin/gfortran
         brew install open-mpi
         pip3 install conan
#       - name: Check Library
#         run: |
#           echo "puts [info tclversion]" | tclsh          
#           cmake --version
#           gfortran --version
#           ompi_info | head
#           python3 --version
#           conan --version
# Build
      - name: Build
        run: |
          mkdir -p build
          cd build
          conan install ..
          cmake -S .. -B ./
          cmake --build ./ --target OpenSees
          cmake --build ./ --target OpenSeesPy
          cp ./lib/OpenSeesPy.dylib ./lib/opensees.so
          cp ./lib/opensees.so ./../artifact/
          cp ./bin/OpenSees ./../artifact/
#          cmake -S .. -B ./
# Verification
      - name: Verification OpenSeesPySP
        run: |
          cd ./EXAMPLES/ExamplePython/
          export PYTHONPATH="../../build/lib/"
          python3 -c "import sys; print(sys.path)"
          python3 example_variable_analysis.py
# Push build
#       - name: Push build Directory
# #         run: gh pr create -B "master" -t " CMake Build on Mac" -b ""
# #         env:
# #           GH_TOKEN: "${GITHUB_TOKEN}"
#         run: |
#           git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
#           git config --global user.name "${GITHUB_ACTOR}"
#           git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#           git add .
#           git commit -m "Push from CMake Build on Mac"
#           git push origin HEAD:${GITHUB_REF}
# Save
      - uses: actions/upload-artifact@v1
        with:
          name: mac-artifact
          path: ./artifact
