name: CMake Build on Ubuntu
env:
  CMAKE_VERSION: 3.20.1
  BUILD_TYPE: Release

on: workflow_dispatch

jobs:
  build:
    name: build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Library
        run: |
         sudo apt-get update
         sudo apt-get install tcl8.6
         sudo apt-get install tcl8.5
         sudo apt-get install gfortran
         sudo apt-get install openmpi-bin
         pip install conan
      - name: Check Library
        run: |
          echo "puts [info tclversion]" | tclsh          
          cmake --version
          gfortran --version
          ompi_info | head
          python --version
          conan --version
      - name: Build
        run: |
          mkdir build
          cd build
          conan install ..
          cmake -S .. -B ./
          cmake --build ./ --target OpenSees
          cmake --build ./ --target OpenSeesPy
          mv lib/OpenSeesPy.dylib lib/opensees.so
# Verification
      - name: Verification OpenSeesPySP
        run: |
          cd ./EXAMPLES/ExamplePython/
          export PYTHONPATH="../../build/lib/"
          python -c "import sys; print(sys.path)"
          python example_variable_analysis.py
